# Generated by Django 3.0.7 on 2020-07-08 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('respiratory_distress', models.BooleanField(default=False)),
                ('appearance', models.BooleanField(default=False)),
                ('risk_factor', models.BooleanField(default=False)),
                ('oxy_saturation', models.BooleanField(default=False)),
                ('respiratory_rate', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='InitialCheckList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symptoms', models.BooleanField(default=False)),
                ('vitals', models.BooleanField(default=False)),
                ('risks', models.BooleanField(default=False)),
                ('hypoxia', models.BooleanField(default=False)),
            ],
        ),
    ]
